/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Loader, FormField } from "../../components/index";
import { getRandomPrompt } from "../../utilities";
import "./CreatePost.css";

export default function CreatePost() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: "",
    prompt: "",
    photo: "",
  });
  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const generateImage = () => {};

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: [e.target.value] });
  };

  const handleSubmit = () => {};

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt);

    setForm({ ...form, prompt: randomPrompt });
  };

  return (
    <section className="container mx-auto">
      <div>
        <h3 className="text-capitalize mt-3 fw-semibold">Create</h3>
        <p className="text-secondary fw-thin text-capitalize d-sm-none d-md-block">
          Create an enchanting assortment of visually striking and imaginative
          images generated by Pixel Fusion and share it with the community
        </p>
      </div>

      <form onSubmit={handleSubmit} className="mt-4">
        <div className="d-flex flex-column gap-3 w-100">
          <FormField
            labelName="Your Name"
            type="text"
            name="name"
            placeholder=" Enter Your Name"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName="Prompt"
            type="text"
            name="prompt"
            placeholder=" What are you thinking about"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe={true}
            handleSurpriseMe={handleSurpriseMe}
          />
          <div className="preview rounded text-secondary">
            {form.photo ? (
              <img
                src={form.photo}
                alt={form.prompt}
                className="w-100 h-100 object-fit-contain"
              />
            ) : (
              <i className="fa-regular fa-image fs-1 opacity-25 text-black"></i>
            )}

            {generatingImg && (
              <div className="position-absolute d-flex justify-content-center align-items-center rounded bg-dark-white w-100 h-100">
                <Loader />
              </div>
            )}
          </div>
        </div>

        <div className="mt-3 d-flex gap-5">
          <button
            type="button"
            className="Button-black-fs"
            onClick={generateImage}
          >
            {generatingImg ? "Generating ..." : "Generate"}
          </button>
        </div>

        <div className="mt-4">
          <p className="text-secondary fs-6">
            Once you have created the image you want, you can share it with the
            community
          </p>
          <button type="submit" className="Button-outline-fs">
            {loading ? "Sharing ..." : "Share"}
          </button>
        </div>
      </form>
    </section>
  );
}
