/* eslint-disable @typescript-eslint/no-unused-vars */
import "./Home.css";
import { useState, useEffect } from "react";
import { Card, FormField, Loader } from "../../components/index";

interface RenderCardProps {
  data: [];
  title: string;
}

const RenderCard = ({ data, title }: RenderCardProps) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return <h3 className="text-capitalize mt-5 fw-semibold">{title}</h3>;
};

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");

  return (
    <section className="mx-auto">
      <div>
        <h3 className="text-capitalize mt-5 fw-semibold">
          An unrivaled showcase of creativity
        </h3>
        <p className="text-secondary fw-thin text-capitalize">
          Explore an enchanting assortment of visually striking and imaginative
          images generated by Pixel Fusion.
        </p>
      </div>
      <div className="mt-5">
        <FormField />
      </div>
      <div className="mt-4">
        {loading ? (
          <div className="d-flex justify-content-center align-items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="text-secondary-emphasis fs-5 text-capitalize fw-light">
                Showing Results for:{" "}
                <span className="fw-normal text-black">{searchText}</span>
              </h2>
            )}
            <div className="d-flex">
              {searchText ? (
                <RenderCard data={[]} title="No Search Results Found" />
              ) : (
                <RenderCard data={[]} title="No Posts Found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
}
